//! Alpine `.apk` package metadata.
//!
//! An Alpine package is not a plain `.tar.gz`: it is two or three gzip streams
//! concatenated -- an optional signature segment, a control segment holding
//! `.PKGINFO`, then the data segment. The generic tar walk declines compressed
//! variants outright ("reported by format only"), so an Alpine package used to
//! yield no members, no metrics and no identity at all, while its siblings
//! (npm, crate, gem, sdist) each read their own metadata member.
//!
//! This reads the control segment the same way `npm.rs` reads
//! `package/package.json`: decompress far enough to reach the metadata, walk
//! headers only, and stop. The data segment -- tens of megabytes on a real
//! package -- is never decompressed, because `.PKGINFO` always precedes it.

use std::io::Read;

use flate2::read::MultiGzDecoder;
use serde_json::{Map as JsonMap, Value as JsonValue};

use crate::error::Error;
use crate::metric;
use crate::output::{Metrics, Values};

/// Decompressed bytes to read before giving up on finding `.PKGINFO`. The
/// signature and control segments together are a few KB on every real package;
/// this is generous enough to absorb an unusual one and small enough that a
/// crafted control segment cannot be used to inflate a scan.
const CONTROL_SCAN_LIMIT: u64 = 4 * 1024 * 1024;

/// tar block size.
const BLOCK: usize = 512;

/// Read a NUL-padded fixed-width tar header field.
fn cstr_field(field: &[u8]) -> &str {
    let end = field.iter().position(|&b| b == 0).unwrap_or(field.len());
    std::str::from_utf8(&field[..end]).unwrap_or("").trim()
}

/// Read a tar octal size field. Malformed fields read as zero, which advances
/// the walk one block at a time rather than trusting a bogus length.
fn octal_field(field: &[u8]) -> usize {
    let text = cstr_field(field);
    usize::from_str_radix(text.trim(), 8).unwrap_or(0)
}

pub(super) fn extract(
    bytes: &[u8],
    values: &mut Values,
    metrics: &mut Metrics,
) -> Result<(), Error> {
    values.insert("archive.format.kind", JsonValue::String("apk".into()));

    // Decompress a bounded prefix and walk the tar headers directly rather
    // than handing the stream to `tar::Archive`. The segments are separate
    // gzip streams whose tars may or may not carry terminating blocks, and a
    // tar reader stops at the first terminator it sees -- which on a signed
    // package is the end of the signature segment, before `.PKGINFO` is
    // reached. Walking blocks is indifferent to where one segment stops and
    // the next begins.
    let mut buf = Vec::new();
    if MultiGzDecoder::new(bytes)
        .take(CONTROL_SCAN_LIMIT)
        .read_to_end(&mut buf)
        .is_err()
        && buf.is_empty()
    {
        return Ok(());
    }

    let mut pkginfo: Option<String> = None;
    let mut signing_keys: Vec<String> = Vec::new();
    let mut off = 0usize;
    while off + BLOCK < buf.len() {
        let block = &buf[off..off + BLOCK];
        let name = cstr_field(&block[..100]);
        if name.is_empty() {
            // Terminator or padding between segments; step over it.
            off += BLOCK;
            continue;
        }
        let size = octal_field(&block[124..136]);
        let body = off + BLOCK;
        let name = name.trim_start_matches("./");
        if name.starts_with(".SIGN.") {
            signing_keys.push(name.to_string());
        } else if name == ".PKGINFO" {
            let end = body.saturating_add(size).min(buf.len());
            pkginfo = Some(String::from_utf8_lossy(&buf[body..end]).into_owned());
            // `.PKGINFO` is the last thing worth reading; the data segment
            // follows and must not be walked.
            break;
        }
        off = body.saturating_add(size.div_ceil(BLOCK) * BLOCK);
    }

    if !signing_keys.is_empty() {
        values.insert(
            "apk.signing_keys",
            JsonValue::Array(signing_keys.into_iter().map(JsonValue::String).collect()),
        );
    }
    metrics.insert(
        metric!("apk.signed"),
        f64::from(u8::from(values.get("apk.signing_keys").is_some())),
    );

    let Some(text) = pkginfo else {
        return Ok(());
    };

    // `.PKGINFO` is `key = value` lines. `depend` and `provides` repeat, so
    // they collect into arrays; everything else is last-wins like the rest of
    // the package readers.
    let mut depends: Vec<JsonValue> = Vec::new();
    let mut provides: Vec<JsonValue> = Vec::new();
    let mut fields = JsonMap::new();
    for line in text.lines() {
        let line = line.trim();
        // The leading comment names the build tool -- `# Generated by melange`
        // or `abuild`. That is the closest thing a package has to a producer,
        // and it distinguishes a distro build from one made on a workstation.
        if let Some(rest) = line.strip_prefix("# Generated by ") {
            values.insert("apk.builder", JsonValue::String(rest.trim().to_string()));
            continue;
        }
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let (key, value) = (key.trim(), value.trim());
        if value.is_empty() {
            continue;
        }
        match key {
            "depend" => depends.push(JsonValue::String(value.to_string())),
            "provides" => provides.push(JsonValue::String(value.to_string())),
            _ => {
                fields.insert(key.to_string(), JsonValue::String(value.to_string()));
            }
        }
    }

    for (key, out) in [
        ("pkgname", "apk.pkgname"),
        ("pkgver", "apk.pkgver"),
        ("pkgdesc", "apk.pkgdesc"),
        ("url", "apk.url"),
        ("license", "apk.license"),
        ("arch", "apk.arch"),
        ("origin", "apk.origin"),
        ("maintainer", "apk.maintainer"),
        ("packager", "apk.packager"),
        ("commit", "apk.commit"),
        ("datahash", "apk.datahash"),
        ("builddate", "apk.builddate"),
    ] {
        if let Some(v) = fields.get(key) {
            values.insert(out, v.clone());
        }
    }
    if !depends.is_empty() {
        metrics.insert(metric!("apk.depend_count"), depends.len() as f64);
        values.insert("apk.depends", JsonValue::Array(depends));
    }
    if !provides.is_empty() {
        values.insert("apk.provides", JsonValue::Array(provides));
    }
    if let Some(size) = fields.get("size").and_then(|v| v.as_str())
        && let Ok(n) = size.parse::<f64>()
    {
        metrics.insert(metric!("apk.declared_size"), n);
    }
    // A package whose `origin` differs from its `pkgname` is a subpackage of
    // another build; when they match it is the primary artifact. Stated as a
    // fact because a package claiming an origin it does not belong to is how a
    // typosquat borrows a real project's provenance.
    if let (Some(name), Some(origin)) = (fields.get("pkgname"), fields.get("origin")) {
        metrics.insert(
            metric!("apk.subpackage"),
            f64::from(u8::from(name != origin)),
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use flate2::{Compression, write::GzEncoder};
    use std::io::Write;

    /// Build the two-segment shape a real package has: a signature tar, then a
    /// control tar, each its own gzip stream.
    fn package(sign: Option<&str>, pkginfo: &str) -> Vec<u8> {
        fn tar_of(name: &str, body: &[u8]) -> Vec<u8> {
            let mut b = tar::Builder::new(Vec::new());
            let mut h = tar::Header::new_gnu();
            h.set_size(body.len() as u64);
            h.set_mode(0o644);
            h.set_cksum();
            b.append_data(&mut h, name, body).unwrap();
            b.into_inner().unwrap()
        }
        fn gz(data: &[u8]) -> Vec<u8> {
            let mut e = GzEncoder::new(Vec::new(), Compression::fast());
            e.write_all(data).unwrap();
            e.finish().unwrap()
        }
        let mut out = Vec::new();
        if let Some(key) = sign {
            out.extend(gz(&tar_of(key, b"-----BEGIN PUBLIC KEY-----")));
        }
        out.extend(gz(&tar_of(".PKGINFO", pkginfo.as_bytes())));
        out
    }

    #[test]
    fn reads_pkginfo_from_the_control_segment() {
        let bytes = package(
            None,
            "# Generated by melange\npkgname = plugin-proposal-decorators\n\
             pkgver = 99.10.9-r0\norigin = plugin-proposal-decorators\n\
             license = MIT\nurl = \ndepend = nodejs\ndepend = python3\nsize = 69873\n",
        );
        let mut values = Values::default();
        let mut metrics = Metrics::default();
        extract(&bytes, &mut values, &mut metrics).unwrap();

        assert_eq!(
            values.get("apk.pkgname").and_then(JsonValue::as_str),
            Some("plugin-proposal-decorators")
        );
        assert_eq!(
            values.get("apk.builder").and_then(JsonValue::as_str),
            Some("melange")
        );
        // An empty value is skipped rather than recorded as an empty claim.
        assert!(values.get("apk.url").is_none());
        assert_eq!(metrics.get("apk.depend_count"), Some(2.0));
        assert_eq!(metrics.get("apk.declared_size"), Some(69873.0));
        assert_eq!(metrics.get("apk.subpackage"), Some(0.0));
        assert_eq!(metrics.get("apk.signed"), Some(0.0));
    }

    #[test]
    fn finds_pkginfo_past_a_signature_segment() {
        let bytes = package(
            Some(".SIGN.RSA.alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub"),
            "pkgname = busybox\npkgver = 1.36.1-r5\norigin = busybox-core\n",
        );
        let mut values = Values::default();
        let mut metrics = Metrics::default();
        extract(&bytes, &mut values, &mut metrics).unwrap();

        assert_eq!(
            values.get("apk.pkgname").and_then(JsonValue::as_str),
            Some("busybox")
        );
        assert_eq!(metrics.get("apk.signed"), Some(1.0));
        let keys = values.get("apk.signing_keys").unwrap();
        assert!(
            keys.as_array().unwrap()[0]
                .as_str()
                .unwrap()
                .contains("alpine-devel")
        );
        // pkgname != origin, so this is a subpackage of another build.
        assert_eq!(metrics.get("apk.subpackage"), Some(1.0));
    }

    #[test]
    fn a_non_package_yields_no_fields() {
        let mut values = Values::default();
        let mut metrics = Metrics::default();
        extract(b"not gzip at all", &mut values, &mut metrics).unwrap();
        assert!(values.get("apk.pkgname").is_none());
    }
}
